### ISSUE TITLE
port

### ISSUE THREAD

**Issue by cirrusflyer** [maxkratz/docker_imapgrab#1]
How can an explicit port be configured in the environmental variables?

**Comment by maxkratz** [comment]
Hi @cirrusflyer!

Currently, there is no possibility to configure the port explicitly with ENVs. The Docker container image uses the default port `993` as it is the default of the underlying python script: https://github.com/ralbear/IMAPbackup/blob/master/imapgrab.py

Would you be interested in changing the port? If this is the case: Would you also want to specify to use SSL/TLS per ENV?

**Comment by cirrusflyer** [comment]
OK, I didn't realize it was using 993 by default.  That's great.  I'm getting an error so it must be something else.  See here:

raise err
socket.error: [Errno 110] Connection timed out

**Comment by maxkratz** [comment]
> OK, I didn't realize it was using 993 by default. That's great. I'm getting an error so it must be something else. See here:

At least, this is what I found in the comments of the python script (linked above).

> raise err
> socket.error: [Errno 110] Connection timed out

Weird. Can you check if the port is open, e.g., using `nmap`? An example command is `nmap -p 993 <your-mailserver>`.

**Comment by maxkratz** [comment]
Could you resolve your problem, @cirrusflyer?

**Comment by cirrusflyer** [comment]
No luck.  Started completely over.  Here's the full log:

IMAP Grab 0.1.4
---
Download option selected
Getting list of mailboxes
Traceback (most recent call last):
  File "imapgrab.py", line 444, in <module>
    imapgrab()
  File "imapgrab.py", line 159, in imapgrab
    IG_backup_mail(ig_options)
  File "imapgrab.py", line 229, in IG_backup_mail
    ig_list = IG_list_mailboxes(ig_list_options)
  File "imapgrab.py", line 188, in IG_list_mailboxes
    ig_imap = imaplib.IMAP4(ig_options.server, ig_options.port)
  File "/usr/lib/python2.7/imaplib.py", line 174, in __init__
    self.open(host, port)
  File "/usr/lib/python2.7/imaplib.py", line 240, in open
    self.sock = socket.create_connection((host, port))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 110] Connection timed out

**Comment by maxkratz** [comment]
@cirrusflyer Were you able to test the port with `nmap` as I suggested?

**Comment by cirrusflyer** [comment]
Only if using this command:   nmap -Pn 993 imap.fastmail.com

Feel free to test Fastmail yourself.  Thanks!

**Comment by cirrusflyer** [comment]
This works better:  nc -z -v imap.fastmail.com 993

**Comment by maxkratz** [comment]
@cirrusflyer I'll check my self and get back to you!

**Comment by maxkratz** [comment]
@cirrusflyer Unfortunately, I can not create a 30-day trial account (Fastmail) without a valid phone number. If you want me to investigate this issue any further please create me a trial account and send me the credentials, for example, via email.

**Comment by cirrusflyer** [comment]
Hello again, I'm starting over as I don't think it's necessarily a Fastmail issue.  But I'm noticing on the Synology when I turn on logging, creating logs files are denied at start.  Can you tell me what PUID the container is running under?  Can this be tailored to the dockeruser as is done with linuxserver.io images?

**Comment by maxkratz** [comment]
> Hello again, I'm starting over as I don't think it's necessarily a Fastmail issue.

Welcome back! Please drop a comment if the issue also occurs with other IMAP/mail providers.

> But I'm noticing on the Synology when I turn on logging, creating logs files are denied at start. Can you tell me what PUID the container is running under? Can this be tailored to the dockeruser as is done with linuxserver.io images?

Can you please open another issue for this (for easier searching by other Github users)? I will then have a look at it.
